# Generated by Django 3.1.3 on 2021-02-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20210219_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
